# Generated by Django 5.0.7 on 2024-09-13 08:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appartement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=10)),
                ('surface', models.DecimalField(decimal_places=2, max_digits=5)),
                ('nombre_pieces', models.IntegerField()),
                ('loyer', models.DecimalField(decimal_places=2, max_digits=8)),
                ('date_ajout', models.DateField(auto_now_add=True)),
                ('est_occupe', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Locataire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('utilisateur', models.CharField(max_length=10)),
                ('date_entree', models.DateField()),
                ('date_sortie', models.DateField(blank=True, null=True)),
                ('appartement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djangoApp.appartement')),
            ],
        ),
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=8)),
                ('date_paiement', models.DateField()),
                ('locataire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djangoApp.locataire')),
            ],
        ),
        migrations.CreateModel(
            name='Preavis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('raison', models.CharField(max_length=255)),
                ('locataire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djangoApp.locataire')),
            ],
        ),
    ]
